### PR TITLE
Fix compatiblity with gulp-sass v5

### PR DESCRIPTION
**Pull request by rabauss**
* Fix extend with compound selectors
* Fix divisions with math.div

### CODE REVIEW

**Comment by denniserdmann** [comment]
Unfortunately, the new math calculations are not compatible with _scssphp_, which is used by the intern contao preprocessor. As mentioned here: https://github.com/scssphp/scssphp/issues/421 a new version is planned, but in an early stage. 

To prevent errors in gulp, i use `node-sass` as compiler instead of the more modern `sass`.

**Extend compound selectors** is something i already fixed in the new nutshell-framework, but missed it fixing here. https://github.com/nutshell-framework/assets/blob/1.x/scss/components/_links.scss#L45-L66

**Comment by rabauss** [comment]
Okay thanks for the advice with the `node-sass`!
I guess we should switch to the ``nutshell-framework`` instead using this package.
Do I need to change the paths in the theme files or how do you refer to the ``nutshell-framework``?

**Comment by denniserdmann** [comment]
> Do I need to change the paths in the theme files or how do you refer to the nutshell-framework?

Yes. Instead of `files/nutshell` you use `assets/nutshell`. Example:

**OLD:**
```
@import '../../../../nutshell/scss/base/page';
```
**NEW:** 
```
@import 'assets/nutshell/scss/base/page';
```

**Comment by rabauss** [comment]
Thanks for the help and much better solutions from https://github.com/nutshell-framework
I migrated to the contao compontent so I will close this PR!

**Pull request closed without merging**
